name: "Update sing-box rule-set"

on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

jobs:
  update-rule-set:
    name: "Update sing-box rule-set"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Setup sing-box"
        env:
          SING_BOX_DEB_URL: "https://github.com/SagerNet/sing-box/releases/download/v1.8.0/sing-box_1.8.0_linux_amd64.deb"
        run: |
            set -Eeuo pipefail
            wget -O sing-box.deb $SING_BOX_DEB_URL
            sudo dpkg -i sing-box.deb
      - name: "Setup python venv"
        run: |
            set -Eeuo pipefail
            python3 -m venv venv
            source venv/bin/activate
            pip3 install -r requirements.txt
      - name: Set env variables
        run: |
          echo "RELEASE_NAME=Released on $(date +%Y%m%d%H%M)" >> $GITHUB_ENV
  
      - name: "Update rule-set"
        run: |
            set -Eeuo pipefail
            source venv/bin/activate
            python3 generate_rule_set.py
      - name: Release and upload
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ env.RELEASE_NAME }}
          draft: false
          prerelease: false
          files: |
            ./rule-set/*.srs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
